#!/bin/bash

#webserver
sudo apt install nginx -y

sudo mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak
sudo cp .nginx.conf.d/default /etc/nginx/sites-enabled/

#php
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:ondrej/php

sudo apt install php7.2 -y
sudo apt install php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mysql php-mbstring php-xml libapache2-mod-php -y

#database - mysql
sudo apt install mysql-server -y
mysql_secure_install

#phpmyadmin
sudo apt install phpmyadmin -y

#run services
sudo service nginx start
sudo service mysql start

#end
echo "Project installed!"

